### PR TITLE
Hebrew Translation Request

### PR DESCRIPTION
**Pull request by Y-PLONI**
Hi there, amazing @高怡飞!

I’ve translated the application into Hebrew, and I would appreciate it if you could push the translation to the repository.

Here are a few points regarding the translation:

Contextual Strings:
Some strings weren’t translated because I need to see them in the application to understand their exact context. If there’s a way to preview them without having to compile the application myself—as I’m not a developer and often struggle with this—I’d really appreciate it.

Release Update:
I’d love it if you could release an update for the application that includes Hebrew. If you think it’s not right to release an update for all users, an alternative would be to compile the application with Hebrew in the same version ([5.0.905.0]) and allow users to download it separately as the latest release.

RTL Support:
The current translation is designed for right-to-left (RTL) alignment. It would be amazing if you could adjust the application to fully support RTL. If that’s not possible, please let me know so I can revise the translation accordingly. Explanation: Since Hebrew characters are aligned to the right and general characters (like periods '.', commas ',', colons ':', etc.) are aligned to the left, issues might arise if the application doesn’t support RTL. RTL support would resolve these potential issues, but if you’re not interested in working on it, Please notify me before the release so I can address these problems.

Please note that when updating strings to English, it’s important to update all strings for all languages as well. I hope this isn’t too much trouble. Feel free to email me if you need assistance—I’m mostly available on weekends. I think a translation website could be helpful for this task, but I understand you’re already exploring this topic. Would you like suggestions for sites?

Thank you for creating such a beautiful and highly useful piece of software!

### CODE REVIEW

**Comment by Gaoyifei1011** [comment]
> Hi there, amazing @高怡飞!
> 
> I’ve translated the application into Hebrew, and I would appreciate it if you could push the translation to the repository.
> 
> Here are a few points regarding the translation:
> 
> Contextual Strings: Some strings weren’t translated because I need to see them in the application to understand their exact context. If there’s a way to preview them without having to compile the application myself—as I’m not a developer and often struggle with this—I’d really appreciate it.
> 
> Release Update: I’d love it if you could release an update for the application that includes Hebrew. If you think it’s not right to release an update for all users, an alternative would be to compile the application with Hebrew in the same version ([5.0.905.0]) and allow users to download it separately as the latest release.
> 
> RTL Support: The current translation is designed for right-to-left (RTL) alignment. It would be amazing if you could adjust the application to fully support RTL. If that’s not possible, please let me know so I can revise the translation accordingly. Explanation: Since Hebrew characters are aligned to the right and general characters (like periods '.', commas ',', colons ':', etc.) are aligned to the left, issues might arise if the application doesn’t support RTL. RTL support would resolve these potential issues, but if you’re not interested in working on it, Please notify me before the release so I can address these problems.
> 
> Please note that when updating strings to English, it’s important to update all strings for all languages as well. I hope this isn’t too much trouble. Feel free to email me if you need assistance—I’m mostly available on weekends. I think a translation website could be helpful for this task, but I understand you’re already exploring this topic. Would you like suggestions for sites?
> 
> Thank you for creating such a beautiful and highly useful piece of software!

As for the first doubt you mentioned, I will provide you with a small packaged test package under this PR after the incorporation of PR for your convenient debugging. Of course, I prefer that you can use the compilation tool on your local computer after deployment and adjustments. Personally, I think compiling this project is relatively easy, if you encounter any doubts during the compilation process, you can ask me individually.

As for the third doubt you mentioned, a user submitted localization support for Arabic before, I found that the language is also RTL layout, so I made relevant adaptations before, this is the effect drawing.

##### -------------------------------

关于第一个您提到的疑惑，我在合并 PR 后，会在这个 PR 下面给您提供一个小型的打包测试包供您方便调试。当然，我更多的是希望您可以在您本地的电脑上使用编译工具部署后并进行调整。我个人认为编译这个项目相对来说是比较容易的，您如果在编译过程中遇到什么疑惑，可以单独向我询问。

关于您提到的第三个疑惑，之前有一位用户提交了关于阿拉伯语的本地化支持，我经调查发现该语言也是 RTL 布局，故我在之前就做了相关适配，这是效果图。

image

**Comment by Gaoyifei1011** [comment]
> Hi there, amazing @高怡飞!
> 
> I’ve translated the application into Hebrew, and I would appreciate it if you could push the translation to the repository.
> 
> Here are a few points regarding the translation:
> 
> Contextual Strings: Some strings weren’t translated because I need to see them in the application to understand their exact context. If there’s a way to preview them without having to compile the application myself—as I’m not a developer and often struggle with this—I’d really appreciate it.
> 
> Release Update: I’d love it if you could release an update for the application that includes Hebrew. If you think it’s not right to release an update for all users, an alternative would be to compile the application with Hebrew in the same version ([5.0.905.0]) and allow users to download it separately as the latest release.
> 
> RTL Support: The current translation is designed for right-to-left (RTL) alignment. It would be amazing if you could adjust the application to fully support RTL. If that’s not possible, please let me know so I can revise the translation accordingly. Explanation: Since Hebrew characters are aligned to the right and general characters (like periods '.', commas ',', colons ':', etc.) are aligned to the left, issues might arise if the application doesn’t support RTL. RTL support would resolve these potential issues, but if you’re not interested in working on it, Please notify me before the release so I can address these problems.
> 
> Please note that when updating strings to English, it’s important to update all strings for all languages as well. I hope this isn’t too much trouble. Feel free to email me if you need assistance—I’m mostly available on weekends. I think a translation website could be helpful for this task, but I understand you’re already exploring this topic. Would you like suggestions for sites?
> 
> Thank you for creating such a beautiful and highly useful piece of software!

[GetStoreAppPackage_5.2.1219.0_x64.msix.zip](https://github.com/user-attachments/files/18264694/GetStoreAppPackage_5.2.1219.0_x64.msix.zip)

**Comment by Y-PLONI** [comment]
I would be happy if you would write to me, so that I can update the translation:
Did you also push the new strings to the he-il folder? [I think so, but I don't know github well enough...]
If not, in which file are they located?
Besides:
I think it might be worth changing the folder name to lowercase [it's currently in uppercase].
You don't have to write to me in Chinese either, because unfortunately I don't know the language. Too bad!

**Comment by Gaoyifei1011** [comment]
> I would be happy if you would write to me, so that I can update the translation: Did you also push the new strings to the he-il folder? [I think so, but I don't know github well enough...] If not, in which file are they located? Besides: I think it might be worth changing the folder name to lowercase [it's currently in uppercase]. You don't have to write to me in Chinese either, because unfortunately I don't know the language. Too bad!

https://github.com/Gaoyifei1011/GetStoreApp/tree/main/GetStoreApp/Strings/he-IL
In this folder, you may need to synchronize the progress of your fork project

The Chinese language was added because the English translation I did was obtained by machine translation, so the Chinese language was retained in case of inaccurate translation

**Pull request merged**
