### PR TITLE
Hebrew translation

### PR DESCRIPTION
**Pull request by Y-PLONI**
I updated the Hebrew translations, 90-95% translated.
I tried to compile to test it for myself, but I couldn't.
Can they be "pushed" into my installed software?

### CODE REVIEW

**Comment by Y-PLONI** [comment]
Due to inconsistencies between the English and Hebrew versions, I am now closing the PR. I will address it later.

**Comment by Gaoyifei1011** [comment]
> I updated the Hebrew translations, 90-95% translated. I tried to compile to test it for myself, but I couldn't. Can they be "pushed" into my installed software?

According to your description, you seem to have encountered a compilation problem. Could you please post a picture of the error to help locate the bug?

**Comment by Y-PLONI** [comment]
@Gaoyifei1011 
Instead, can you pass the strings to a translation site?
That would simplify the process.

**Comment by Gaoyifei1011** [comment]
> @Gaoyifei1011 Instead, can you pass the strings to a translation site? That would simplify the process.

As for online website translation, I have been researching this for some time, but I still haven't fully figured it out. If you are interested in working on online website translation, you are welcome to join this work.

##### ------------------------------

关于在线网站翻译这件事，我曾经研究过一段时间，但至今仍未完全弄清楚。如果您有兴趣参与在线网站翻译的工作，欢迎您加入这一工作中。

**Pull request closed without merging**
